# Generated by Django 2.2.2 on 2019-06-16 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_auto_20190615_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='wasPlayed',
            field=models.BooleanField(default=False),
        ),
    ]
