# Generated by Django 2.2.6 on 2019-10-03 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_song_wasplayed'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='website',
            field=models.CharField(default='unknown', max_length=30),
        ),
    ]
